apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: octopus-config
  labels:
    app: octopus
data:
  nac-passive-scanner-traffic-topic.yaml: |
    streamingService: "KAFKA"
    kafkaCon:
      brokers:
        - "qkafka01.p09.eng.in03.qualys.com:50360"
        - "qkafka02.p09.eng.in03.qualys.com:50360"
        - "qkafka03.p09.eng.in03.qualys.com:50360"
      topic: "nac-passive-scanner-traffic-topic"
      distributed: false
      clientID: qflow
    minio:
      endpoint: "minio.eng.sjc01.qualys.com"
      accessKeyID: "AKIAIOSFODNN7EXAMPLE"
      secretAccessKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      bucketName: "qlake"
      useSSL: false
    uploadSize: 8192000

  nac-passive-scanner-topic.yaml: |
    streamingService: "KAFKA"
    kafkaCon:
      brokers:
        - "qkafka01.p09.eng.in03.qualys.com:50360"
        - "qkafka02.p09.eng.in03.qualys.com:50360"
        - "qkafka03.p09.eng.in03.qualys.com:50360"
      topic: "nac-passive-scanner-topic"
      distributed: false
      clientID: qflow
    minio:
      endpoint: "minio.eng.sjc01.qualys.com"
      accessKeyID: "AKIAIOSFODNN7EXAMPLE"
      secretAccessKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      bucketName: "qlake"
      useSSL: false
    uploadSize: 8192000
